language: python
python: 
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
    - "pip install -r requirements.txt"
    - "pip install ."

script: 
    - python hf3lint.py -f term share/bc_000_notcorrect.xml
    - python hf3lint.py -f term share/bc_000_correct.xml 
    - python hf3lint.py -f term share/bc_001_correct.xml 
    - python hf3lint.py -f term share/hf3_000.xml
